### ISSUE TITLE
invalid go version

### ISSUE THREAD

**Issue by hosainxade** [ImAyrix/fallparams#1]
Hello how can i fix that?
<img width="1030" alt="Screenshot 1402-10-12 at 14 46 14" src="https://github.com/ImAyrix/fallparams/assets/127223084/e3ec7369-b7c6-433d-ab92-e259dcb5d9c1">

**Comment by phoelion** [comment]
in the `go.mod` file, change the go version to 1.23,
it worked for me.
@hosainxade @ImAyrix

**Comment by ImAyrix** [comment]
Hello, please run the installation command again because I have provided a new update. If you still have the same problem, update GO and try again. Please let me know if the problem persists. Thank you.

### Fallparams
```
go install github.com/ImAyrix/fallparams@latest
```

### Go
+ https://go.dev/doc/install

@hosainxade @phoelion

**Comment by hosainxade** [comment]
Thank you that worked!

**Comment by hosainxade** [comment]
Thank you that worked!
