### ISSUE TITLE
go: errors parsing go.mod:

### ISSUE THREAD

**Issue by 0xsheet** [ImAyrix/fallparams#5]
go build main.go
go: errors parsing go.mod:
/home/kali/fallparams/go.mod:5: unknown directive: toolchain

**Comment by yossev** [comment]
This feature is not yet widely adopted and may cause issues in environments not prepared for it.

Removing it temporarily till its stable should be good enough.

Will make a PR for it.

**Comment by ImAyrix** [comment]
Hi, update GO and try again.

https://go.dev/doc/install
